### ISSUE TITLE
organizing discussion

### ISSUE THREAD

**Issue by cddesja** [mdbeckman/USCOTS-2021-EDA#1]
Should we use Google Slides for the discussions. If so, [here's a link](https://docs.google.com/presentation/d/18S_VhhrVDre-rfd01wajJMm6w8c-l2nqE7i6Su-bKMQ/edit?usp=sharing) that we can edit. 

Also, who is going to be the lead? Introducing the session, leading the large group discussion (at least initially), etc? 

@mdbeckman @llendway

**Comment by llendway** [comment]
I think it would be great to use the Google Doc for the following (from the June 16 meeting notes):

- (1:30-1:40pm; 10 min) Opening remarks about EDA (and IDA initial data analysis)--each sharing: 
    - why we're interested in the topic 
    - our current perspectives (individually) 
    - which courses/student populations are front of mind

- (2:05-2:15pm; 10 min) small groups review & discuss various guidance for EDA--e.g., (EACH OF US NEEDS TO PICK ONE - I ALREADY SAID I'D DO WICKHAM AND GROLEMUND)
    - Velleman & Hoaglin (2012). Exploratory data analysis. In *APA handbook of research methods in psychology* <doi.org/10.1037/13621-003>
    - Shan (2020). An extensive step by step guide to exploratory data analysis.  *Towards data science.*
    - Wickham & Grolemund (2020). *R for Data Science* <r4ds.had.co.nz> (Lisa)

I will be working on this tomorrow. I assume Matt is doing to be the lead :)
